// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCommandTemplate = "command_template"

// CommandTemplate mapped from table <command_template>
type CommandTemplate struct {
	ID          int32      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name        string     `gorm:"column:name;not null" json:"name"`
	Protocol    *string    `gorm:"column:protocol" json:"protocol"`
	Description *string    `gorm:"column:description" json:"description"`
	Host        *string    `gorm:"column:host" json:"host"`
	Port        *string    `gorm:"column:port" json:"port"`
	MonitorID   *int32     `gorm:"column:monitor_id" json:"monitor_id"`
	UpdatedAt   *time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	CreatedAt   *time.Time `gorm:"column:created_at;default:now()" json:"created_at"`
}

// TableName CommandTemplate's table name
func (*CommandTemplate) TableName() string {
	return TableNameCommandTemplate
}
