// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMCondition = "m_condition"

// MCondition mapped from table <m_condition>
type MCondition struct {
	ID               int32   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CalculateType    *string `gorm:"column:calculate_type" json:"calculate_type"`
	NextLogicType    *string `gorm:"column:next_logic_type" json:"next_logic_type"`
	Value            *string `gorm:"column:value" json:"value"`
	SearchRule       *string `gorm:"column:search_rule;comment:ex: person.item.[]array.name" json:"search_rule"`
	NextMConditionID *int32  `gorm:"column:next_m_condition_id" json:"next_m_condition_id"`
}

// TableName MCondition's table name
func (*MCondition) TableName() string {
	return TableNameMCondition
}
