// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMonitorCondition = "monitor_condition"

// MonitorCondition mapped from table <monitor_condition>
type MonitorCondition struct {
	ID          int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	MonitorID   *int32 `gorm:"column:monitor_id" json:"monitor_id"`
	ConditionID *int32 `gorm:"column:condition_id" json:"condition_id"`
}

// TableName MonitorCondition's table name
func (*MonitorCondition) TableName() string {
	return TableNameMonitorCondition
}
