// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMonitor = "monitor"

// Monitor mapped from table <monitor>
type Monitor struct {
	ID           int32   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Column       *string `gorm:"column:column" json:"column"`
	Timeout      *int32  `gorm:"column:timeout" json:"timeout"`
	Interval     *int32  `gorm:"column:interval" json:"interval"`
	MConditionID *int32  `gorm:"column:m_condition_id" json:"m_condition_id"`
}

// TableName Monitor's table name
func (*Monitor) TableName() string {
	return TableNameMonitor
}
