// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMqttCommand = "mqtt_command"

// MqttCommand mapped from table <mqtt_command>
type MqttCommand struct {
	ID        int32   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CommandID *int32  `gorm:"column:command_id" json:"command_id"`
	Topic     *string `gorm:"column:topic" json:"topic"`
	Header    *string `gorm:"column:header" json:"header"`
	Message   *string `gorm:"column:message" json:"message"`
	Type      *string `gorm:"column:type" json:"type"`
}

// TableName MqttCommand's table name
func (*MqttCommand) TableName() string {
	return TableNameMqttCommand
}
