// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Wilson",
            "url": "https://github.com/littlebluewhite",
            "email": "wwilson008@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/header_template/": {
            "get": {
                "description": "Get all header templates",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "header_template"
                ],
                "summary": "Show all header templates",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/header_template.HeaderTemplate"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "header_template"
                ],
                "summary": "Create header templates",
                "parameters": [
                    {
                        "description": "header template body",
                        "name": "header_template",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/header_template.HeaderTemplateCreate"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/header_template.HeaderTemplate"
                            }
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "header_template"
                ],
                "summary": "Delete header templates",
                "parameters": [
                    {
                        "description": "header_template id",
                        "name": "ids",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "delete successfully",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "header_template"
                ],
                "summary": "Update header templates",
                "parameters": [
                    {
                        "description": "modify header template body",
                        "name": "header_template",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/header_template.HeaderTemplateUpdate"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "update successfully",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/header_template/{id}": {
            "get": {
                "description": "Get header templates by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "header_template"
                ],
                "summary": "Show header templates",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "header template id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/header_template.HeaderTemplate"
                        }
                    }
                }
            }
        },
        "/ping/list": {
            "get": {
                "description": "test list ping",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ping"
                ],
                "summary": "return list ping",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/ping.SwaggerListPing"
                            }
                        }
                    }
                }
            }
        },
        "/ping/test": {
            "get": {
                "description": "test ping",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ping"
                ],
                "summary": "test ping",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ping.SwaggerPing"
                        }
                    }
                }
            }
        },
        "/time_template/": {
            "get": {
                "description": "Get all time templates",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "time_template"
                ],
                "summary": "Show all time templates",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/time_template.TimeTemplate"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "time_template"
                ],
                "summary": "Create time templates",
                "parameters": [
                    {
                        "description": "time template body",
                        "name": "time_template",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/time_template.TimeTemplateCreate"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/time_template.TimeTemplate"
                            }
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "time_template"
                ],
                "summary": "Delete time templates",
                "parameters": [
                    {
                        "description": "time_template id",
                        "name": "ids",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "delete successfully",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "time_template"
                ],
                "summary": "Update time templates",
                "parameters": [
                    {
                        "description": "modify time template body",
                        "name": "time_template",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/time_template.TimeTemplateUpdate"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "update successfully",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/time_template/{id}": {
            "get": {
                "description": "Get time templates by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "time_template"
                ],
                "summary": "Show time templates",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "time template id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/time_template.TimeTemplate"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "header_template.HeaderTemplate": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "header_template.HeaderTemplateCreate": {
            "type": "object",
            "required": [
                "data",
                "name"
            ],
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "header_template.HeaderTemplateUpdate": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "ping.SwaggerListPing": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer",
                    "example": 20
                },
                "name": {
                    "type": "string",
                    "example": "wilson"
                }
            }
        },
        "ping.SwaggerPing": {
            "type": "object",
            "properties": {
                "example": {
                    "type": "string",
                    "example": "asdfasdf"
                }
            }
        },
        "time_template.TimeDatum": {
            "type": "object",
            "properties": {
                "end_date": {
                    "type": "string"
                },
                "end_time": {
                    "type": "string"
                },
                "interval_seconds": {
                    "type": "integer"
                },
                "m_condition": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "m_condition_type": {
                    "type": "string"
                },
                "repeat_type": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                }
            }
        },
        "time_template.TimeDatumCreate": {
            "type": "object",
            "required": [
                "end_time",
                "m_condition",
                "start_date",
                "start_time"
            ],
            "properties": {
                "end_date": {
                    "type": "string"
                },
                "end_time": {
                    "type": "string"
                },
                "interval_seconds": {
                    "type": "integer"
                },
                "m_condition": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "m_condition_type": {
                    "type": "string"
                },
                "repeat_type": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                }
            }
        },
        "time_template.TimeDatumUpdate": {
            "type": "object",
            "required": [
                "end_time",
                "m_condition",
                "repeat_type",
                "start_date",
                "start_time"
            ],
            "properties": {
                "end_date": {
                    "type": "string"
                },
                "end_time": {
                    "type": "string"
                },
                "interval_seconds": {
                    "type": "integer"
                },
                "m_condition": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "m_condition_type": {
                    "type": "string"
                },
                "repeat_type": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                }
            }
        },
        "time_template.TimeTemplate": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "time_data": {
                    "$ref": "#/definitions/time_template.TimeDatum"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "time_template.TimeTemplateCreate": {
            "type": "object",
            "required": [
                "name",
                "time_data"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "time_data": {
                    "$ref": "#/definitions/time_template.TimeDatumCreate"
                }
            }
        },
        "time_template.TimeTemplateUpdate": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "time_data": {
                    "$ref": "#/definitions/time_template.TimeDatumUpdate"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "localhost:5487",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Schedule-Command swagger API",
	Description:      "This is a schedule-command server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
