definitions:
  header_template.HeaderTemplate:
    properties:
      data:
        items:
          type: integer
        type: array
      id:
        type: integer
      name:
        type: string
    type: object
  header_template.HeaderTemplateCreate:
    properties:
      data:
        items:
          type: integer
        type: array
      name:
        type: string
    required:
    - data
    - name
    type: object
  header_template.HeaderTemplateUpdate:
    properties:
      data:
        items:
          type: integer
        type: array
      id:
        type: integer
      name:
        type: string
    required:
    - id
    type: object
  ping.SwaggerListPing:
    properties:
      age:
        example: 20
        type: integer
      name:
        example: wilson
        type: string
    type: object
  ping.SwaggerPing:
    properties:
      example:
        example: asdfasdf
        type: string
    type: object
  time_template.TimeDatum:
    properties:
      end_date:
        type: string
      end_time:
        type: string
      interval_seconds:
        type: integer
      m_condition:
        items:
          type: integer
        type: array
      m_condition_type:
        type: string
      repeat_type:
        type: string
      start_date:
        type: string
      start_time:
        type: string
    type: object
  time_template.TimeDatumCreate:
    properties:
      end_date:
        type: string
      end_time:
        type: string
      interval_seconds:
        type: integer
      m_condition:
        items:
          type: integer
        type: array
      m_condition_type:
        type: string
      repeat_type:
        type: string
      start_date:
        type: string
      start_time:
        type: string
    required:
    - end_time
    - m_condition
    - start_date
    - start_time
    type: object
  time_template.TimeDatumUpdate:
    properties:
      end_date:
        type: string
      end_time:
        type: string
      interval_seconds:
        type: integer
      m_condition:
        items:
          type: integer
        type: array
      m_condition_type:
        type: string
      repeat_type:
        type: string
      start_date:
        type: string
      start_time:
        type: string
    required:
    - end_time
    - m_condition
    - repeat_type
    - start_date
    - start_time
    type: object
  time_template.TimeTemplate:
    properties:
      created_at:
        type: string
      id:
        type: integer
      name:
        type: string
      time_data:
        $ref: '#/definitions/time_template.TimeDatum'
      updated_at:
        type: string
    type: object
  time_template.TimeTemplateCreate:
    properties:
      name:
        type: string
      time_data:
        $ref: '#/definitions/time_template.TimeDatumCreate'
    required:
    - name
    - time_data
    type: object
  time_template.TimeTemplateUpdate:
    properties:
      id:
        type: integer
      name:
        type: string
      time_data:
        $ref: '#/definitions/time_template.TimeDatumUpdate'
    required:
    - id
    type: object
host: localhost:5487
info:
  contact:
    email: wwilson008@gmail.com
    name: Wilson
    url: https://github.com/littlebluewhite
  description: This is a schedule-command server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Schedule-Command swagger API
  version: "2.0"
paths:
  /header_template/:
    delete:
      parameters:
      - description: header_template id
        in: body
        name: ids
        required: true
        schema:
          items:
            type: integer
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: delete successfully
          schema:
            type: string
      summary: Delete header templates
      tags:
      - header_template
    get:
      description: Get all header templates
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/header_template.HeaderTemplate'
            type: array
      summary: Show all header templates
      tags:
      - header_template
    patch:
      consumes:
      - application/json
      parameters:
      - description: modify header template body
        in: body
        name: header_template
        required: true
        schema:
          items:
            $ref: '#/definitions/header_template.HeaderTemplateUpdate'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: update successfully
          schema:
            type: string
      summary: Update header templates
      tags:
      - header_template
    post:
      consumes:
      - application/json
      parameters:
      - description: header template body
        in: body
        name: header_template
        required: true
        schema:
          items:
            $ref: '#/definitions/header_template.HeaderTemplateCreate'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/header_template.HeaderTemplate'
            type: array
      summary: Create header templates
      tags:
      - header_template
  /header_template/{id}:
    get:
      description: Get header templates by id
      parameters:
      - description: header template id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/header_template.HeaderTemplate'
      summary: Show header templates
      tags:
      - header_template
  /ping/list:
    get:
      description: test list ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/ping.SwaggerListPing'
            type: array
      summary: return list ping
      tags:
      - ping
  /ping/test:
    get:
      description: test ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ping.SwaggerPing'
      summary: test ping
      tags:
      - ping
  /time_template/:
    delete:
      parameters:
      - description: time_template id
        in: body
        name: ids
        required: true
        schema:
          items:
            type: integer
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: delete successfully
          schema:
            type: string
      summary: Delete time templates
      tags:
      - time_template
    get:
      description: Get all time templates
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/time_template.TimeTemplate'
            type: array
      summary: Show all time templates
      tags:
      - time_template
    patch:
      consumes:
      - application/json
      parameters:
      - description: modify time template body
        in: body
        name: time_template
        required: true
        schema:
          items:
            $ref: '#/definitions/time_template.TimeTemplateUpdate'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: update successfully
          schema:
            type: string
      summary: Update time templates
      tags:
      - time_template
    post:
      consumes:
      - application/json
      parameters:
      - description: time template body
        in: body
        name: time_template
        required: true
        schema:
          items:
            $ref: '#/definitions/time_template.TimeTemplateCreate'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/time_template.TimeTemplate'
            type: array
      summary: Create time templates
      tags:
      - time_template
  /time_template/{id}:
    get:
      description: Get time templates by id
      parameters:
      - description: time template id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/time_template.TimeTemplate'
      summary: Show time templates
      tags:
      - time_template
swagger: "2.0"
